/**
 * @fileoverview gRPC-Web generated client stub for orderbook
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v5.29.3
// source: orderbook.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.orderbook = require('./orderbook_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.orderbook.OrderBookServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.orderbook.OrderBookServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.orderbook.AddOrderRequest,
 *   !proto.orderbook.OrderResponse>}
 */
const methodDescriptor_OrderBookService_AddOrder = new grpc.web.MethodDescriptor(
  '/orderbook.OrderBookService/AddOrder',
  grpc.web.MethodType.UNARY,
  proto.orderbook.AddOrderRequest,
  proto.orderbook.OrderResponse,
  /**
   * @param {!proto.orderbook.AddOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.orderbook.OrderResponse.deserializeBinary
);


/**
 * @param {!proto.orderbook.AddOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.orderbook.OrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.orderbook.OrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.orderbook.OrderBookServiceClient.prototype.addOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/orderbook.OrderBookService/AddOrder',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_AddOrder,
      callback);
};


/**
 * @param {!proto.orderbook.AddOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.orderbook.OrderResponse>}
 *     Promise that resolves to the response
 */
proto.orderbook.OrderBookServicePromiseClient.prototype.addOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/orderbook.OrderBookService/AddOrder',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_AddOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.orderbook.CancelOrderRequest,
 *   !proto.orderbook.OrderResponse>}
 */
const methodDescriptor_OrderBookService_CancelOrder = new grpc.web.MethodDescriptor(
  '/orderbook.OrderBookService/CancelOrder',
  grpc.web.MethodType.UNARY,
  proto.orderbook.CancelOrderRequest,
  proto.orderbook.OrderResponse,
  /**
   * @param {!proto.orderbook.CancelOrderRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.orderbook.OrderResponse.deserializeBinary
);


/**
 * @param {!proto.orderbook.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.orderbook.OrderResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.orderbook.OrderResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.orderbook.OrderBookServiceClient.prototype.cancelOrder =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/orderbook.OrderBookService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_CancelOrder,
      callback);
};


/**
 * @param {!proto.orderbook.CancelOrderRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.orderbook.OrderResponse>}
 *     Promise that resolves to the response
 */
proto.orderbook.OrderBookServicePromiseClient.prototype.cancelOrder =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/orderbook.OrderBookService/CancelOrder',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_CancelOrder);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.orderbook.GetOrderBookRequest,
 *   !proto.orderbook.OrderBookResponse>}
 */
const methodDescriptor_OrderBookService_GetOrderBook = new grpc.web.MethodDescriptor(
  '/orderbook.OrderBookService/GetOrderBook',
  grpc.web.MethodType.UNARY,
  proto.orderbook.GetOrderBookRequest,
  proto.orderbook.OrderBookResponse,
  /**
   * @param {!proto.orderbook.GetOrderBookRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.orderbook.OrderBookResponse.deserializeBinary
);


/**
 * @param {!proto.orderbook.GetOrderBookRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.orderbook.OrderBookResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.orderbook.OrderBookResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.orderbook.OrderBookServiceClient.prototype.getOrderBook =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/orderbook.OrderBookService/GetOrderBook',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_GetOrderBook,
      callback);
};


/**
 * @param {!proto.orderbook.GetOrderBookRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.orderbook.OrderBookResponse>}
 *     Promise that resolves to the response
 */
proto.orderbook.OrderBookServicePromiseClient.prototype.getOrderBook =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/orderbook.OrderBookService/GetOrderBook',
      request,
      metadata || {},
      methodDescriptor_OrderBookService_GetOrderBook);
};


module.exports = proto.orderbook;

